Elcodi\Component\Zone\Entity\Zone:
    type: entity
    repositoryClass: Elcodi\Component\Zone\Repository\ZoneRepository
    table: zone
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        locations:
            column: locations
            type: string
            length: 512
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean
            nullable: true

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
