parameters:

    #
    # Factories
    #
    elcodi.factory.zone.class: Elcodi\Component\Zone\Factory\ZoneFactory

    #
    # Services
    #
    elcodi.matcher.zone.class: Elcodi\Component\Zone\Services\ZoneMatcher
    elcodi.finder.zone.class: Elcodi\Component\Zone\Services\ZoneFinder
