services:

    #
    # Directors
    #
    elcodi.director.zone:
        class: Elcodi\Component\Core\Services\ObjectDirector
        arguments:
            - @elcodi.object_manager.zone
            - @elcodi.repository.zone
            - @elcodi.factory.zone
