services:

    #
    # Services
    #
    elcodi.matcher.zone:
        class: %elcodi.matcher.zone.class%
        arguments:
            location_manager: @elcodi.location_provider

    elcodi.finder.zone:
        class: %elcodi.finder.zone.class%
        arguments:
            zone_repository: @elcodi.repository.zone
            zone_matcher: @elcodi.matcher.zone
