services:

    #
    # Services
    #
    elcodi.matcher.zone:
        class: %elcodi.matcher.zone.class%
        arguments:
            - @elcodi.location_provider

    elcodi.finder.zone:
        class: %elcodi.finder.zone.class%
        arguments:
            - @elcodi.repository.zone
            - @elcodi.matcher.zone
